version: '3.7'
services:
  elasticsearch:
    image: elasticsearch:8.3.2
    container_name: elasticsearch
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      discovery.type: "single-node"
      ELASTIC_PASSWORD: "admin123"
      xpack.security.enabled: "false"
    networks:
      - elk

  kibana:
    image: kibana:8.3.2
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
      ELASTICSEARCH_USERNAME: "kibana_system"
      ELASTICSEARCH_PASSWORD: "admin123"
    depends_on:
      - elasticsearch
    networks:
      - elk

  logstash:
    image: logstash:8.3.2
    container_name: logstash
    command: logstash -f /usr/share/logstash/pipeline/logstash.conf
    ports:
      - 9600:9600
      - 5044:5044
    volumes:
      # - ./logstash/logstash.yml:/usr/share/logstash/logstash.yml:ro,z
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro,z
      - ./logs:/usr/share/logstash/logs:ro,z
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    depends_on:
      - elasticsearch
    networks:
      - elk

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin123"
    depends_on:
      - logstash
    networks:
      - elk

volumes:
  setup:
  elasticsearch:


networks:
  elk:
    driver: bridge
